---
title: ""
---

```{=html}
<div class="tomie-ascii" aria-label="ASCII portrait of Tomie (Junji Ito)" role="img">
<pre class="tomie-frame tomie-frame-a">
                 ,,;;;;;;;;;;;;;;;;;;;;;,,
             ,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,
          ,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,
        ,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,
      ,;;;;;;;;;;''''''''''''''''''''''''''';;;;;;;;;,
     ;;;;;;;;''                                  '';;;;;;
    ;;;;;;'                                         ';;;;;
   ;;;;;'         .:;;;;;;;;;;;;;;;;;;;;;;:.          ';;;;;
  ;;;;;        .:;;;;;;;;;;;;;;;;;;;;;;;;;;;;:.         ;;;;
  ;;;;        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;         ;;;;
  ;;;;       ;;;;;;'                       ';;;;;;       ;;;;
  ;;;;       ;;;;     .;;;;.         .;;;;.    ;;;;      ;;;;
  ;;;;       ;;;;    ;;;@@@;;       ;;;@@@;;   ;;;;      ;;;;
  ;;;;       ;;;;   ;; @@@@@ ;;    ;; @@@@@ ;; ;;;;      ;;;;
  ;;;;       ;;;;   ;; @@o@@ ;;    ;; @@o@@ ;; ;;;;      ;;;;
  ;;;;       ;;;;    ;;;@@@;;       ;;;@@@;;   ;;;;      ;;;;
  ;;;;       ;;;;     ''''''           ''''''   ;;;;     ;;;;
  ;;;;       ;;;;;             **              ;;;;;     ;;;;
  ;;;;        ;;;;;           *  *            ;;;;;     ;;;;
  ;;;;;        ;;;;;                        ;;;;;       ;;;;;
   ;;;;;        ;;;;;         ______        ;;;;;       ;;;;
   ;;;;;;        ;;;;;;      /      \      ;;;;;;      ;;;;;
    ;;;;;;        ';;;;;;   |   __   |    ;;;;;;       ;;;;;
     ;;;;;;;        ';;;;;;  \_/  \_/   ;;;;;;        ;;;;;;
      ';;;;;;;        ';;;;;;;       ;;;;;;;         ;;;;;;
        ';;;;;;;;       ';;;;;;;;;;;;;;;'          ;;;;;;;
          ';;;;;;;;;,      '';;;;;;;;''         ,;;;;;;;;
             ';;;;;;;;;;;,,           ,,,;;;;;;;;;;;;
               ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
                  ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;
       \\\\\\\\\\\\\\\\\|||||||||||||||||||||////////////////
        \\\\\\\\\\\\\\\\|||||||||||||||||||||///////////////
         \\\\\\\\\\\\\\\|||||||||||||||||||||//////////////
          \\\\\\\\\\\\\\|||||||||||||||||||||/////////////
           \\\\\\\\\\\\\|||||||||||||||||||||////////////
            \\\\\\\\\\\\|||||||||||||||||||||///////////
             \\\\\\\\\\\|||||||||||||||||||||//////////
              \\\\\\\\\\|||||||||||||||||||||/////////
               \\\\\\\\\|||||||||||||||||||||////////
                \\\\\\\\|||||||||||||||||||||///////
</pre>
<pre class="tomie-frame tomie-frame-b" aria-hidden="true">
                 ,,;;;;;;;;;;;;;;;;;;;;;,,
             ,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,
          ,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,
        ,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,
      ,;;;;;;;;;;''''''''''''''''''''''''''';;;;;;;;;,
     ;;;;;;;;''                                  '';;;;;;
    ;;;;;;'                                         ';;;;;
   ;;;;;'         .:;;;;;;;;;;;;;;;;;;;;;;:.          ';;;;;
  ;;;;;        .:;;;;;;;;;;;;;;;;;;;;;;;;;;;;:.         ;;;;
  ;;;;        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;         ;;;;
  ;;;;       ;;;;;;'                       ';;;;;;       ;;;;
  ;;;;       ;;;;     .;;;;.         .;;;;.    ;;;;      ;;;;
  ;;;;       ;;;;    ;;;^^^;;       ;;;^^^;;   ;;;;      ;;;;
  ;;;;       ;;;;   ;; ^^*^^ ;;    ;; ^^*^^ ;; ;;;;      ;;;;
  ;;;;       ;;;;   ;; ^^o^^ ;;    ;; ^^o^^ ;; ;;;;      ;;;;
  ;;;;       ;;;;    ;;;^^^;;       ;;;^^^;;   ;;;;      ;;;;
  ;;;;       ;;;;     ''''''           ''''''   ;;;;     ;;;;
  ;;;;       ;;;;;             **              ;;;;;     ;;;;
  ;;;;        ;;;;;           *  *            ;;;;;     ;;;;
  ;;;;;        ;;;;;      .,-~~~~~-,.         ;;;;;     ;;;;;
   ;;;;;        ;;;;;   ,~~  _____  ~~,      ;;;;;       ;;;;
   ;;;;;;        ;;;;;;/  \|/|/|/|/|/ \     ;;;;;;      ;;;;;
    ;;;;;;        ';;;;;;   |/|/|/|/|    ;;;;;;         ;;;;;
     ;;;;;;;        ';;;;;;  `~~~~~'   ;;;;;;         ;;;;;;
      ';;;;;;;        ';;;;;;;       ;;;;;;;         ;;;;;;
        ';;;;;;;;       ';;;;;;;;;;;;;;;'          ;;;;;;;
          ';;;;;;;;;,      '';;;;;;;;''         ,;;;;;;;;
             ';;;;;;;;;;;,,           ,,,;;;;;;;;;;;;
               ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
                  ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;
       \\\\\\\\\\\\\\\\\|||||||||||||||||||||////////////////
        \\\\\\\\\\\\\\\\|||||||||||||||||||||///////////////
         \\\\\\\\\\\\\\\|||||||||||||||||||||//////////////
          \\\\\\\\\\\\\\|||||||||||||||||||||/////////////
           \\\\\\\\\\\\\|||||||||||||||||||||////////////
            \\\\\\\\\\\\|||||||||||||||||||||///////////
             \\\\\\\\\\\|||||||||||||||||||||//////////
              \\\\\\\\\\|||||||||||||||||||||/////////
               \\\\\\\\\|||||||||||||||||||||////////
                \\\\\\\\|||||||||||||||||||||///////
</pre>
</div>
```

::: {.about-text}

Hi, I'm Shusuke Ioku, a Ph.D. candidate in Political Science at the University of Rochester. I study historical political economy, combining formal theory with micro-level historical data to understand statebuilding and political extremism, particularly how the *periphery* of the state shaped state development and political radicalization.

My current research explores how radical elites undermined democracy in interwar Japan by organizing through [civic associations](research.qmd#fascist-paper), particularly in the northern periphery where anti-center sentiment ran deep. I also study how jurisdictional competition among feudal rulers in Tokugawa Japan enabled peripheral peasants to pursue [mass exit](research.qmd#exit-paper) instead of violent confrontation, constraining extractive authority from below. A third line of work examines how statebuilders in early medieval Japan deliberately hollowed out their own administrative apparatus by privatizing extraction, initiating [feudal fragmentation](research.qmd#feudalism-paper) most prominently in peripheral regions where central authority was weak.

### Contact

- **Email**: <button class="copy-email-btn" type="button" onclick="navigator.clipboard.writeText('iokushusuke@gmail.com'); this.textContent='Copied'; setTimeout(() => this.textContent='Copy', 1200);">Copy</button>
- **GitHub**: [shusuke-ioku](https://github.com/shusuke-ioku)

:::
